tests: remove the snap profiler from the test suite
snapcore/snapd pull request #10047
Opened 2021-03-18 11:42 UTC by sergiocazzolato

The profiler snap is not being used and for that raeson the idea is to
get rid of it.

In case it is needed to profile a test, it could be manually installed.

2021-03-23 14:52 UTC, anonymouse64 requested changes
I think before we remove a somewhat complicated snap like this from the source tree, we should find a new home for it somewhere in case we find we need it again. 

I still am of the opinion that it would be nice to have a repo like `test-snapd-snaps` which houses all of these `test-snapd-*` snaps which can't just be `snap pack`ed (or maybe all of them too) where we can put all of these, such that the snapd repo isn't full of them, but we still have them in a convenient and central location where they can be kept up to date more easily without pr's to snapd and without individual developers running snapcraft to build these snaps and upload them.

2021-04-08 14:43 UTC, sergiocazzolato commented
@anonymouse64 the change is done, the idea is to start storing the snaps which are built using snapcraft command in tests/lib/snaps/store

2021-04-08 15:01 UTC, anonymouse64 reviewed
lgtm, please update the description of the PR to reflect that the snap has just been moved around and is no longer referenced in prepare.sh, but still in the git tree

2021-04-08 15:02 UTC, anonymouse64 approved these changes

2021-04-12 13:42 UTC, merged