interfaces: builtin: update permitted paths to be compatible with UC20
snapcore/snapd pull request #10194
Opened 2021-04-25 11:45 UTC by kubiko

Core20 does not have populated `/bin` and `/sbin` directories, instead those are symbolic links to `/usr/bin` and `/usr/sbin` respectively.
Apparmor profiles need to reflect this, otherwise we have disparity what is allowed on pre uc20 and uc20 systems

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

2021-04-28 02:49 UTC, alexmurray requested changes
Should this also include changes for /lib -> /usr/lib too? - I have annotated a couple which are missing in the diff but there is also ones in interfaces/builtin/hardware_observe.go, interfaces/builtin/kernel_module_control.go and another in interfaces/builtin/account_control.go that I think should probably also be included. Also there are a heap in interfaces/apparmor/template.go that may also need updating too.

I think it would be very beneficial to introduce some sort of check to catch any future additions of apparmor profile rules that do not honor usrmerge'd systems (ie that use specific /bin, /sbin or /lib paths).

Finally I am surprised we haven't been hit by this previously on classic systems but this is a good change to have.

2021-04-28 02:49 UTC, alexmurray commented on interfaces/builtin/network_control.go
>  /lib/resolvconf/* ix,
Does this need to also change to be:

```
/{,usr/}lib/resolvconf/* ix,
```

2021-04-28 02:49 UTC, alexmurray commented on interfaces/builtin/network_manager.go
>  /lib/resolvconf/* ix,
Does this need to also change to be:

```
/{,usr/}lib/resolvconf/* ix,
```

2021-04-28 08:50 UTC, kubiko commented
> Should this also include changes for /lib -> /usr/lib too? - I have annotated a couple which are missing in the diff but there is also ones in interfaces/builtin/hardware_observe.go, interfaces/builtin/kernel_module_control.go and another in interfaces/builtin/account_control.go that I think should probably also be included. Also there are a heap in interfaces/apparmor/template.go that may also need updating too.
> 
> I think it would be very beneficial to introduce some sort of check to catch any future additions of apparmor profile rules that do not honor usrmerge'd systems (ie that use specific /bin, /sbin or /lib paths).
> 
> Finally I am surprised we haven't been hit by this previously on classic systems but this is a good change to have.

that's good point about `/lib` `/usr/lib` I missed that one.
It did confuse me that none of our spread test catch this, I'd expect at least some to hit it. We should indeed have tests covering this for the future.
I'm also very surprised I was first one hitting this (in my case it was udisk2 and `mount`) :)

I will add changes addressing also `/lib` and check default template.

2021-04-29 21:43 UTC, kubiko commented on interfaces/builtin/network_control.go
>  /lib/resolvconf/* ix,
yep, added

2021-04-29 21:43 UTC, kubiko commented on interfaces/builtin/network_manager.go
>  /lib/resolvconf/* ix,
yep, added as well

2021-04-29 21:44 UTC, kubiko commented
@alexmurray I have now updated also template and other interfaces with changes for /lib as you suggested.

2021-05-10 04:48 UTC, alexmurray approved these changes
Thanks @kubiko - this looks good to me.

2021-05-10 08:38 UTC, mvo5 approved these changes
Thanks for catching this

2021-05-10 08:39 UTC, merged