tests: allow spread tests to skip the OOM test
snapcore/snapd pull request #10764
Opened 2021-09-10 11:30 UTC by mardy

The quota-groups-systemd-accounting test has been seen failing on Arch
with these logs:

  https://paste.ubuntu.com/p/YB5xpM5FYR/

While it's not totally clear why the OOM was triggered (there don't
appear to be any processes inside the control group), the test does
indeed create a couple of control groups with a ridiculously low amount
of memory, and one theory about this failure is that the systemd process
itself got momentarily assigned to the group.

In any case, the test is not interested in checking whether an OOM
occurred or not, so we do not want to trigger a failure if it happened.

2021-09-10 12:21 UTC, bboozzoo commented on tests/lib/prepare-restore.sh
> +        if dmesg|grep "oom-killer"; then
It's probably enough to have tests set it to a non empty value
```suggestion
    if [  -n "${SKIP_OOM_CHECK-}" ]; then
        if dmesg|grep "oom-killer"; then
```

2021-09-10 14:01 UTC, anonymouse64 requested changes
Rather than ignore the oom-killer message here (which I agree is erroneous and not related to the actual failure), I would rather see us just bump the memory limit in the test empty groups (the "poisoned branch" in the comments) to something that doesn't cause systemd to choke like this. There should be no processes from us in those groups at all so we don't anticipate seeing oom-killer there, but there could still be an oom-killer message if something goes wrong with the `sub` group since it has go-example-webserver in it.

2021-09-13 06:20 UTC, mardy commented
> Rather than ignore the oom-killer message here (which I agree is erroneous and not related to the actual failure), I would rather see us just bump the memory limit in the test empty groups (the "poisoned branch" in the comments) to something that doesn't cause systemd to choke like this.

Makes sense. I change the limits to 50MB and 49MB.

2021-09-13 16:05 UTC, anonymouse64 approved these changes
lgtm

2021-09-14 07:16 UTC, bboozzoo approved these changes
LGTM, title doesn't match the contents of the branch now.

2021-09-14 10:08 UTC, merged