Bboozzoo/cgroupv2 test and systems with memlock fix
snapcore/snapd pull request #10826
Opened 2021-09-22 12:31 UTC by bboozzoo

Based on top of #10803. The main change is introducing `setrlimit(RLIMIT_MEMLOCK..)` for working around the old BPF object memory accounting used by pre 5.11 kernels. The problem is only visible on Debian SId, where the system uses unified hierarchy and ships a 5.10 kernel. The relevant patches are:
- https://github.com/snapcore/snapd/commit/fdb85196384373a9af8757daa863874c1f36c0a7
- https://github.com/snapcore/snapd/commit/a2fc705051ff908bb6b29ea7e8f30f756256ef98

2021-09-22 13:35 UTC, bboozzoo commented
@alexmurray you probably know more about this, I see in the logs:
```
wrz 22 15:32:19 galeon audit[755574]: AVC apparmor="DENIED" operation="capable" profile="/usr/lib/snapd/snap-confine" pid=755574 comm="snap-confine" capability=39  capname="bpf"
```
which was fixed by https://github.com/snapcore/snapd/pull/10826/commits/fdb85196384373a9af8757daa863874c1f36c0a7, but then apparmor 2.x seems to choke on this and fail, so I had to revert the patch. However, I don't see any BPF operations failing, so maybe we don't need it and just live with the denial? I would really like to avoid the rabbit hole of probing apparmor_parser for support of `capability bpf` and patching snap confine apparmor profile at runtime.

2021-09-23 07:40 UTC, mvo5 approved these changes
Looks good, thank you

2021-09-23 07:40 UTC, mvo5 commented on cmd/libsnap-confine-private/device-cgroup-support.c
> +    /* this should be more than enough for creating the map and loading the
Maybe
```
//  640K ought to be enough for anybody.
const rlim_t min_memlock_limit = 640 * 1024;
```
for lolz ?

2021-09-23 09:47 UTC, mardy requested changes
Just a small change :-)

2021-09-23 09:47 UTC, mardy commented on cmd/libsnap-confine-private/device-cgroup-support.c
> +        return old_limit;
```
    (void)sc_set_effective_identity(old);
```
before returning :-)

2021-09-23 13:01 UTC, alexmurray requested changes
See comments in the diff - I think this can be simplified by making use of `_sc_cgroup_v2_set_memlock_limit` within `_sc_cgroup_v2_adjust_memlock_limit` itself.

2021-09-24 08:46 UTC, mardy approved these changes
LGTM!

2021-09-24 13:05 UTC, alexmurray approved these changes
LGTM - thanks :)

2021-09-27 07:23 UTC, merged