tests: fix security-udev-input-subsystem test
snapcore/snapd pull request #11390
Opened 2022-02-14 23:38 UTC by sergiocazzolato

Permission denied could also be returned instead of 'Operation not permitted'.

2022-02-15 08:36 UTC, mardy requested changes
I'm afraid that this change is not what we want, because when the error is "Permission denied" it means that our cgroup configuration was not setup/enforced, and this is exactly what this test is for.

What we could do, is disabling this test altogether and create an issue for it.

2022-02-15 14:13 UTC, sergiocazzolato commented
@mardy hi, thanks for taking a look, this is an old one, at some point @anonymouse64 confirmed that both messages could be expected, I don't remember the reason, I would add a comment in the test explaining the reason once Ian confirms that.

2022-02-15 16:46 UTC, anonymouse64 approved these changes
looks fine to me as a temporary change until someone has time to modify these tests to not have the wrong assumption that the evaluation order of LSMs in the kernel is non-deterministic

2022-02-16 10:10 UTC, stolowski approved these changes
LGTM

2022-02-16 10:10 UTC, stolowski commented on tests/main/security-udev-input-subsystem/task.yaml
>      # to the cgroup, we see a DAC denial.
@anonymouse64 thanks for extra insight into this!

2022-02-16 11:04 UTC, mardy approved these changes
After Ian's explanation, I'm fine with the change :-) Thanks!

2022-02-16 11:20 UTC, merged