i/b/desktop,unity7: remove name= specification on D-Bus signals
snapcore/snapd pull request #11846
Opened 2022-06-03 14:10 UTC by mardy

All the rules touched in this commit are about D-Bus signals. We want
the D-Bus daemon to forward them to any listening processes, so it's not
correct to limit them to the D-Bus daemon only.

Opening as a draft as I'm not sure this is correct. The fact that all D-Bus signals have this specification makes me thing that maybe this is intentional and that the rule might be like this because of some internal logic to the D-Bus AppArmor module of how signals are being treated.

Incidentally, I wonder if having the `label=unconfined` label is correct -- don't we want these signals to potentially reach any listening process, including confined snap applications?

@alexmurray, @jhenstridge: waiting for your feedback, on whether this is needed/correct at all.

2022-06-08 00:04 UTC, alexmurray requested changes
LGTM.

2022-06-08 00:04 UTC, alexmurray approved these changes
LGTM!

2022-06-20 09:39 UTC, mvo5 approved these changes
Thank you

2022-06-20 09:40 UTC, mvo5 commented
A word from @jhenstridge would be nice before merging this but it looks correct to me

2022-07-25 08:41 UTC, jhenstridge approved these changes
These all look good. None of the altered AppArmor rules look like they were intended for communication with the bus daemon itself.

2022-07-25 10:17 UTC, merged