interfaces/system-packages-doc: allow read-only access to /usr/share/cups/doc-root/ and /usr/share/gimp/2.0/help/ (https://bugzilla.mozilla.org/show_bug.cgi?id=1770462)
snapcore/snapd pull request #11861
Opened 2022-06-10 06:47 UTC by lissyx

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

2022-06-10 06:51 UTC, lissyx commented
This is similar to https://github.com/snapcore/snapd/pull/11588, original report was about GIMP's doc, and I came accross cups as a coincidence but why not fix it at the same time ...

2022-06-10 07:04 UTC, mardy approved these changes
Thanks, LGTM!

2022-06-10 07:29 UTC, alexmurray requested changes
I think this also needs associated entries in `systemPackagesDocConnectedPlugAppArmor` unless I am missing something?

2022-06-10 07:35 UTC, lissyx commented
> I think this also needs associated entries in `systemPackagesDocConnectedPlugAppArmor` unless I am missing something?

Thanks, I've added them

2022-06-10 08:41 UTC, bboozzoo approved these changes
LGTM

2022-06-10 08:41 UTC, bboozzoo commented on tests/main/interfaces-system-packages-doc/task.yaml
> +    echo text >/usr/share/gimp/2.0/help/content
Thanks for updating the test

2022-06-10 11:45 UTC, alexmurray approved these changes
LGTM - whilst not relevant for this PR, but it would be good to reduce all the copy-pasta in this interface and instead perhaps have a list of all the various paths that we want to allow access to and then just iterate over this to generate the various AppArmor rules and etc

2022-06-10 17:05 UTC, lissyx commented
@mardy @alexmurray So there are a few tests that are failing but I'm unsure why. Also, even though I did sign the CLA, the tooling seems unaware of that. Let me know if I need to do anything more.

2022-06-13 06:20 UTC, bboozzoo commented
@lissyx that's ok, the failures are unrelated.

Hm the CLA check keeps failing though. I wonder what's going on. DId you use the same email address as in the commit? Did you receive a confirmation from launchpad the CLA was signed?

2022-06-14 08:35 UTC, merged