interfaces/apparmor: add missing apparmor rules for journal namespaces
snapcore/snapd pull request #11889
Opened 2022-06-16 12:06 UTC by Meulengracht

Currently the path in apparmor allows writes to the journal socket/stdout, which resides in `/run/systemd/journal`, which is fine for the default journal. However when journal namespaces are used, a new folder will be created for each namespace. Their paths will look like `/run/systemd/journal.{namespace}`

To support journal namespaces, this change is needed

2022-06-20 09:13 UTC, mvo5 approved these changes
This looks fine to me but it also needs a security review

2022-06-20 13:01 UTC, alexmurray requested changes
There is nothing in this PR which specifies what problem there currently is and hence why this change is needed - which makes it hard to assess any possible security tradeoff etc. Can the PR please be updated to provide some background info on this change? Thanks.

2022-06-20 13:32 UTC, alexmurray approved these changes
Thanks for the updated description - do the namespaces follow any particular naming convention? Basically I am wondering can we be stricter than just `*`. Otherwise LGTM.

2022-06-20 13:52 UTC, Meulengracht commented
> Thanks for the updated description - do the namespaces follow any particular naming convention? Basically I am wondering can we be stricter than just `*`. Otherwise LGTM.

By inspecting systemd's source code they are pretty generous and allow anything that fits this regex `[a-zA-Z0-9\@:\-\_.\\]+`, we could use that instead of *

2022-06-21 07:24 UTC, Meulengracht commented
> > By inspecting systemd's source code they are pretty generous and allow anything that fits this regex [a-zA-Z0-9@:-_.\]+, we could use that instead of *
> 
> aren't we though only interested in the namespace we introduce ourselves? so don't we have a bit more control there?

Correct, if we determine it during runtime we can write a very accurate rule, I have updated this PR to be that, but this is now completely different. I can always revert to the previous approach.

2022-06-21 07:59 UTC, mvo5 approved these changes
Thanks, it's nice that this is super precise now.

2022-06-21 12:12 UTC, alexmurray requested changes
Excuse my ignorance, but does the quota name come from a user/admin - ala https://snapcraft.io/docs/quota-groups - and as such, would it be possible for them to try and inject arbitrary apparmor rules via a crafted quota name? I suspect this may be the case, so at a minimum this path should be quoted like so:

```go
template := `  "/run/systemd/%[1]s/socket" w,
  # 'r' shouldn't be needed here, but journald doesn't leak anything so allow
  "/run/systemd/%[1]s/stdout" rw
`
```

On a related note - excuse my ignorance on quota-groups but do we have any constraints on how these are specified/validated?

2022-06-21 12:26 UTC, pedronis commented
@alexmurray quota group names should be validated via naming.ValidateQuotaGroup, which has fairly strict rules like for snap names

2022-06-21 14:38 UTC, pedronis requested changes
There is a bit of layring confusion and extra complexity in being so precise, as now we in the end had to teach details about journal namespace to the apparmor backend.

2022-06-22 03:45 UTC, alexmurray approved these changes
Thanks for the pointer to `naming.ValidateQuotaGroup` @pedronis - from a security PoV this LGTM but as @pedronis perhaps this is too much of a layering violation now. Either way, I am satisfied that this shouldn't allow admins to inject arbitrary apparmor rules.

2022-06-22 06:33 UTC, Meulengracht commented on interfaces/apparmor/backend.go
> +				if strings.HasPrefix(l.Bind, path.Join(dirs.SnapSystemdRunDir, "journal.")) {
Yea we prefix namespaces with `snap-`, I'll revert to the previous approach but with the regex

2022-06-22 16:11 UTC, pedronis approved these changes
lgtm, but comment about comments

2022-06-24 09:36 UTC, Meulengracht commented on interfaces/apparmor/template.go
> +  /run/systemd/journal{,.snap-*}/stdout rw, # 'r' shouldn't be needed, but journald
Really good point, thanks! I've updated the PR.

2022-06-27 08:21 UTC, merged