interfaces/display-control: allow changing brightness value
snapcore/snapd pull request #11934
Opened 2022-07-01 12:17 UTC by bugraaydogar

Once a developer would like to change the brigness of the display, they get the following AppArmor denials. This PR aims to fix that.

```
apparmor="DENIED" operation="open" profile="snap.my-app.awesome-ui" name=""  pid=1859 comm="bash" requested_mask="wc" denied_mask="wc" fsuid=0 ouid=0
```

2022-07-01 13:14 UTC, MiguelPires commented
Thanks for this. I added the "Needs security review" label since it's an interface change

2022-07-01 13:15 UTC, bugraaydogar commented on interfaces/builtin/display_control.go
> +/sys/devices/**/**/drm/card[0-9]/card[0-9]*/**_backlight/brightness, w
can we? It is a symlink so I was not sure.
```
lrwxrwxrwx  1 root root 0 Haz 30 11:59 intel_backlight -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight
```

2022-07-02 07:54 UTC, mardy reviewed
I'm unsure about granting direct access, since we already have rules for GNOME and KDE; but indeed, in those systems (like core) where neither is present, we have no alternative to a direct file access.

I wonder, though, if there should be an interface attribute specifying a different flavor? Maybe I'm overthinking it, since AFAIK the GNOME and KDE interfaces are just convinence APIs and I guess nothing bad happens if one plays with the brightness settings directly...

I think the current approach is fine, I just raise the point in case someone sees any risk there.

2022-07-02 07:54 UTC, mardy commented on interfaces/builtin/display_control.go
> +/sys/devices/**/**/drm/card[0-9]/card[0-9]*/**_backlight/brightness, w
For symbolic links, we need to allow both paths (symbolic link name and target) in order to have it working.

IMHO it makes sense to list the symlink too.

About the "target" rule, I guess it should be either
```suggestion
/sys/devices/**/**/drm/card[0-9]/**_backlight/brightness, w
```
or
```suggestion
/sys/devices/**/**/drm/card[0-9]/card[0-9]*/*_backlight/brightness, w
```

2022-07-04 06:49 UTC, bugraaydogar commented on interfaces/builtin/display_control.go
> +/sys/devices/**/**/drm/card[0-9]/card[0-9]*/**_backlight/brightness, w
Thanks, updated after the comments.

2022-07-05 07:11 UTC, mardy approved these changes
LGTM, but let's wait for the security review before merging this.

2022-07-11 02:39 UTC, alexmurray requested changes
I don't think the symlink name itself is needed - just the target - since AppArmor rules only use the target - as such I think the `/sys/class/backlight/...` rule should be removed for clarity.

2022-07-11 09:36 UTC, bugraaydogar commented
The PR is modified as per @alexmurray comment.

2022-07-11 09:44 UTC, MiguelPires approved these changes
LGTM

2022-07-11 12:11 UTC, alexmurray approved these changes
LGTM!

2022-07-11 12:49 UTC, MiguelPires reviewed
The comma is misplaced

2022-07-11 12:49 UTC, MiguelPires commented on interfaces/builtin/display_control.go
> +/sys/devices/**/**/drm/card[0-9]/card[0-9]*/*_backlight/brightness, w
```suggestion
/sys/devices/**/**/drm/card[0-9]/card[0-9]*/*_backlight/brightness w,
```

2022-07-11 12:54 UTC, bugraaydogar commented on interfaces/builtin/display_control.go
> +/sys/devices/**/**/drm/card[0-9]/card[0-9]*/*_backlight/brightness, w
Thanks Miguel, very good catch.

2022-07-11 16:55 UTC, MiguelPires approved these changes
Thank you

2022-07-12 07:31 UTC, merged