boot,gadget: add new `device.TpmLockoutAuthUnder()` and use it
snapcore/snapd pull request #11946
Opened 2022-07-11 08:30 UTC by mvo5

Create a helper in `gadget/device/encrypt.go:TpmLockoutAuthUnder()`
that is used to retrieve the path of the TPM lockout auth data.

This is then used in the boot package and will also be used when
reseting the DA lockout counter.

This is split out of PR#11935.

2022-07-11 09:28 UTC, mardy approved these changes
LGTM, thanks!

2022-07-11 15:16 UTC, pedronis requested changes
we restrained from changes the tests in boot so far

2022-07-11 15:16 UTC, pedronis commented on boot/makebootable_test.go
> +		c.Check(lockoutAuthFile, Equals, device.TpmLockoutAuthUnder(boot.InstallHostFDESaveDir))
we didn't use device in the tests so far, it's probably a good idea to continue not to for a while, to be sure that we didn't change anything

2022-07-11 15:16 UTC, pedronis commented on boot/seal_test.go
> +			c.Check(lockoutAuthFile, Equals, device.TpmLockoutAuthUnder(boot.InstallHostFDESaveDir))
same

2022-07-12 07:43 UTC, pedronis approved these changes
thanks

2022-07-12 09:45 UTC, merged