Update u2f_devices.go
snapcore/snapd pull request #12305
Opened 2022-11-07 20:45 UTC by orlinum

Add new device :  TOKEN2 FIDO2 Security Key
https://www.token2.eu/home

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

2022-12-05 15:35 UTC, mvo5 approved these changes
Thanks, this looks fine. 

Fwiw, I checked https://github.com/Yubico/libfido2/blob/main/udev/70-u2f.rules#L153 and it has the same data.

2022-12-07 02:44 UTC, alexmurray approved these changes
LGTM!

2022-12-15 10:49 UTC, mvo5 commented
@orlinum Thanks again for your contribution - could you please sign our CLA https://ubuntu.com/legal/contributors so that the cla-check test passes. Thanks!

2024-02-27 22:04 UTC, ernestl requested changes
The vendor and product ID should we associated with the existing "Thetis Key".
TOKEN2 was added [here](https://github.com/snapcore/snapd/pull/12662) and match info [here](https://www.token2.com/shop/page/using-token2-fido2-keys-under-linux).

2024-02-27 22:42 UTC, ernestl commented
Superseded by https://github.com/snapcore/snapd/pull/12466. Closing.

2024-02-27 22:42 UTC, closed without merging