Refactor: Replace IsNotFound usages for errors.Is(err, &NotFoundError{})
snapcore/snapd pull request #12538
Opened 2023-02-01 14:07 UTC by ZeyadYasser

This is just a simple refactor to replace [`IsNotFound()`](https://github.com/snapcore/snapd/blob/master/asserts/database.go#L48) usages for `errors.Is(err, &NotFoundError{})`.

2023-02-01 15:20 UTC, MiguelPires requested changes
Thank you for opening a PR and taking care of this TODO. The implementation of `Is` is creates an infinite recursion loop whenever it's called. You can verify this by running the unit tests with `go test` or you can run the `run-checks` script which does that as well as running some static checks. The [HACKING.md](https://github.com/snapcore/snapd/blob/master/HACKING.md) document has more information on building and testing snapd

2023-02-01 15:20 UTC, MiguelPires commented on asserts/database.go
> +	return errors.Is(err, &NotFoundError{})
This creates a recursion loop which causes a stack overflow panic

2023-02-01 21:06 UTC, ZeyadYasser commented on asserts/database.go
> +	return errors.Is(err, &NotFoundError{})
Thank you for pointing out the [HACKING.md](https://github.com/snapcore/snapd/blob/master/HACKING.md) document. I am running Fedora, so I was having trouble with some dependencies.
I fixed the issue, installed an Ubuntu VM and ran the unit tests there instead.

2023-02-01 21:08 UTC, ZeyadYasser commented on asserts/database.go
> +	return errors.Is(err, &NotFoundError{})
I noticed that it was advised in the [HACKING.md](https://github.com/snapcore/snapd/blob/master/HACKING.md#guidelines-for-contributors) document to not force push.
Please let me know if I need to squash my commits before merging.

2023-02-06 09:50 UTC, MiguelPires commented on asserts/database.go
> +	return errors.Is(err, &NotFoundError{})
Yes, if you could squash before merging (after the PR has 2 approvals), that would be great. Thanks

2023-02-06 14:13 UTC, MiguelPires approved these changes
LGTM, thanks for the updates

2023-02-06 14:14 UTC, MiguelPires commented
The tests are failing due to some trouble downloading dependencies but it's not related to this PR. I'll re-run them once the issue is resolved

2023-02-09 13:16 UTC, Meulengracht approved these changes
LGTM. Thanks for helping us clean up the TODOs!

2023-02-09 16:02 UTC, merged