interfaces: add nfs-mount interface
snapcore/snapd pull request #12799
Opened 2023-05-05 16:38 UTC by atomcult

Should be pretty self-explanatory, this just adds a new interface to allow for NFS shares to be mounted.

2023-05-09 07:12 UTC, mvo5 reviewed
Thanks for working on this, this looks nice!

It would be super nice to get a spread test for this too,  we already have some nfs related test in `tests/main/nfs-support` so maybe/hopefully writing one that installs a test-snap with nfs-mount that then mounts a local FS should be relatively straightforward. There are many examples for interfaces tests in `tests/main/interface-*` that are hopefully helpful.

2023-05-09 07:12 UTC, mvo5 commented on interfaces/builtin/nfs_mount.go
> + * Copyright (C) 2018 Canonical Ltd
This probably needs a tweak to 2023 :)

2023-05-09 07:12 UTC, mvo5 commented on interfaces/builtin/nfs_mount_test.go
> + * Copyright (C) 2016-2017 Canonical Ltd
This will also need an update

2023-05-25 16:20 UTC, atomcult commented
Thanks for the feedback!

I've gotten some spread tests written up, but to do the actual testing I needed to make a snap that contains binary content (`mount.nfs` and `umount.nfs` from the `nfs-common` package). How do we typically handle cases like this? I noticed that there are quite a few snaps used for spread tests in the global snap store (which also seem to have their source in the snapd source tree). I was initially going to simply register and upload the snap myself, with the intention of transferring it to the snapd team at a later point, but, since this is for a new interface, the store rejected the snap (having not recognized the `nfs-mount` plug).

You can find the snap in question [here](https://github.com/atomcult/snapd/tree/nfs-interface-tests/tests/lib/snaps/store/test-snapd-nfs-mount) and the corresponding task [here](https://github.com/atomcult/snapd/blob/nfs-interface-tests/tests/main/interfaces-nfs-mount/task.yaml).

Any advice on how to proceed would be greatly appreciated!

2023-06-15 11:01 UTC, pedronis commented
this conceptually is similar to cifs-mount I think

2023-06-21 11:49 UTC, atomcult commented
In terms of spread tests? As far as I've seen the CIFS interface is lacking spread tests.
If you mean that it's similar to `cifs-mount` more generally, then yes, that's actually what I based my code on :slightly_smiling_face:

2024-03-06 08:48 UTC, zyga commented
The code looks good. I will add a spread test if that is easy-ish.

2024-03-08 23:13 UTC, alexmurray approved these changes
LGTM!

2024-03-12 14:13 UTC, zyga commented
I've merged master into this to see how it fares in CI. I'll push updated tests when ready.

2024-03-13 10:41 UTC, zyga commented
Wait, I accidentally pushed some unrelated NFS things into this branch. Let me back out that patch.

2024-03-13 10:43 UTC, zyga requested changes

2024-03-13 10:43 UTC, zyga commented on interfaces/builtin/nfs_mount_test.go
> +	spec := &apparmor.Specification{}
This is no longer allowed. Sadly we require a non-zero value since d8a2e847e507caae0d7162ffb5a46fb8186a376f.

2024-03-13 10:50 UTC, zyga approved these changes
Looks good to me now

2024-03-13 10:50 UTC, zyga commented on interfaces/builtin/nfs_mount.go
> + * Copyright (C) 2018 Canonical Ltd
Fixed

2024-03-13 10:50 UTC, zyga commented on interfaces/builtin/nfs_mount_test.go
> + * Copyright (C) 2016-2017 Canonical Ltd
Fixed

2024-03-13 10:50 UTC, zyga commented on interfaces/builtin/nfs_mount_test.go
> +	spec := &apparmor.Specification{}
Fixed

2024-03-13 12:40 UTC, pedronis approved these changes
thanks

2024-03-14 07:40 UTC, merged