interfaces/upower-observe: allow it in core-desktop
snapcore/snapd pull request #12863
Opened 2023-06-01 11:24 UTC by sergio-costas

This change is required to allow ubuntu-desktop-session and other snaps to connect to upower-observe in core-desktop.

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

2023-06-06 11:00 UTC, jhenstridge reviewed
I know we've had this patch in the UCD branch of snapd for a while, but I don't think it is suitable to be upstreamed as is, since it also changes how the declaration applies to non-implicit upower-observe slots provided by snaps.

One idea was to try and match based on snap IDs to detect whether we're an implicit slot, but the `slot-snap-id` constraint isn't currently supported for a slot allow/deny-connection rule.

2023-06-07 11:40 UTC, sergio-costas commented
@jhenstridge How could I implement that?

2023-06-21 11:43 UTC, pedronis commented
it requires changes to asserts/ifacedecls.go

2023-06-21 11:47 UTC, pedronis requested changes
we can't do this this way. If I understand the goal is to let connect to the implicit slot either on classic or core?

2023-06-22 07:18 UTC, pedronis commented
> What if I do it conditional to have upowerd running?

doesn't change the issue that we do not want to change the policy for app slots

2023-06-29 15:38 UTC, sergio-costas commented
@pedronis So... I presume that the idea is to only allow snapped `upower` in Core/Core Desktop... is that?

2023-08-08 13:44 UTC, pedronis commented
I proposed this code along the lines of what was discussed here:

https://github.com/snapcore/snapd/pull/13062

2023-09-08 07:24 UTC, pedronis commented
closing in favor of https://github.com/snapcore/snapd/pull/13062 that has been approved by @alexmurray

2023-09-08 07:24 UTC, closed without merging