interfaces/account-control: grant access to the files and executables…
snapcore/snapd pull request #12860
Opened 2023-05-29 10:37 UTC by bugraaydogar

Hi,

core22 snap enables `pam_faillock` by default and therefore while using it, the developers face the following denials;

```
audit: type=1400 audit(1683639151.460:3331): apparmor="DENIED" operation="exec" profile="snap-name" name="/usr/lib/core/lockout-not-enabled.sh" pid=52701 comm="wasp" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
audit: type=1400 audit(1683639151.460:3332): apparmor="DENIED" operation="open" profile="snap-name" name="/etc/security/faillock.conf" pid=25489 comm="wasp" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1683639151.460:3333): apparmor="DENIED" operation="exec" profile="snap-name" name="/usr/sbin/pam_extrausers_chkpwd" pid=52701 comm="wasp" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
audit: type=1400 audit(1683639151.460:3334): apparmor="DENIED" operation="exec" profile="snap-name" name="/usr/sbin/unix_chkpwd" pid=52701 comm="wasp" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
audit: type=1400 audit(1683639151.460:3335): apparmor="DENIED" operation="open" profile="snap-name" name="/etc/shadow" pid=25489 comm="wasp" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
The proposed changes address these denials.

Thanks,
Bugra

2023-06-05 08:21 UTC, mvo5 approved these changes
Thanks, this looks fine.

2023-06-05 08:23 UTC, mvo5 commented
As an idle wondering - should we extend our `tests/main/interfaces-account-control` to catch this? I.e. ensure there are no new denials after the test was run?

2023-06-05 09:03 UTC, valentindavid commented
> As an idle wondering - should we extend our `tests/main/interfaces-account-control` to catch this? I.e. ensure there are no new denials after the test was run?

We just need to add `ubuntu-core-22-64` I believe.

2023-06-05 09:04 UTC, valentindavid approved these changes

2023-06-05 09:06 UTC, valentindavid commented
> 



> > As an idle wondering - should we extend our `tests/main/interfaces-account-control` to catch this? I.e. ensure there are no new denials after the test was run?
> 
> We just need to add `ubuntu-core-22-64` I believe.

But it is already there. It should have failed.

2023-06-05 10:13 UTC, mvo5 commented
> > 
> 
> > > As an idle wondering - should we extend our `tests/main/interfaces-account-control` to catch this? I.e. ensure there are no new denials after the test was run?
> > 
> > 
> > We just need to add `ubuntu-core-22-64` I believe.
> 
> But it is already there. It should have failed.

I created https://github.com/snapcore/snapd/pull/12867 which should probably just merged/cherry picked into this one here - it shows that it's just apparmor DENIALS in the logs.

2023-06-05 10:49 UTC, valentindavid reviewed
I would like to retract my review. This is needed for authentication. I am wondering if this is really the role of `account-control`. I need to find out what the use case is for needing authentication within a snap.

2023-06-05 11:02 UTC, mvo5 commented
This should probably also include a test test addition like https://github.com/snapcore/snapd/compare/master...mvo5:check-account-control-common-auth?expand=1 (running it locally now and fine to chery pick once I know it works).

2023-06-15 10:58 UTC, pedronis commented
@bugraaydogar I think we need some more context, which/what kind of snap  is running and what is it trying to do that gets those denials?

2023-06-15 11:55 UTC, bugraaydogar commented
Hi @pedronis, 

The Linux PAM provides developers fine-grained authentication mechanism. One example use case is that; you have a web interface to manage your Ubuntu Core device and existing users on the device can authenticate via the web interface. Here is some arguments why a developer might choose to use Linux PAM;

- Linux PAM is an authentication system and provides a way to control and give access to some specific processes. 
- Developers do not want to maintain different databases for users if you consider the webui example.
- The idea of using "System user" is too generic and system-user can do anything on the device. 

Unfortunately, I could not fetch more data then this since the implementation details were not known to the people that I engaged with.

2023-06-19 06:57 UTC, alexmurray requested changes
FWIW I agree with @valentindavid and I am not sure this interface is the right place for these additions. `account-control` is for adding / removing accounts etc - whereas PAM is concerned with authentication of an existing account.

As such, perhaps a new interface `linux-pam` or somesuch is needed? Then in developing such a new interface, the various use-cases can hopefully be more fully articulated and captured by that new interface.

2023-07-13 10:59 UTC, pedronis commented
Whatever we ultimately do, adding these executables here is not the right approach. As their function is not consistent witht this interface in particular. Closing this.

2023-07-13 10:59 UTC, closed without merging