cmd/snap-device-helper: handle bind and unbind commands
snapcore/snapd pull request #12874
Opened 2023-06-07 09:16 UTC by valentindavid

2023-06-19 06:49 UTC, alexmurray requested changes
Thanks for this - could you please update the description of the PR with some more info? Why is this change needed? Also would it be possible to add a spread test as well?

2023-06-19 08:59 UTC, ernestl approved these changes
Looks good

2023-08-09 11:39 UTC, valentindavid commented
> Why is this change needed? 

It was already explained with: "Instead it would generate an error.". But there was a typo. I have also added a commit comment.

> Also would it be possible to add a spread test as well?

Done.

2023-08-09 11:39 UTC, valentindavid commented
Also, I have phrased it a bit more obvious in the commit message: "We have been generating error as "unknown action", which
pollutes the logs and confuse users."

2023-08-15 12:19 UTC, pedronis approved these changes
thanks, small remark

2023-08-15 12:19 UTC, pedronis commented on cmd/snap-device-helper/snap-device-helper.c
> +    } else if (sc_streq(action, "unbind")) {
this probably should have a comment about expecting a remove later that will be then acted on

2023-09-18 07:44 UTC, pedronis commented
@alexmurray marked it security-high as there are further PRs based on this one

2023-09-19 03:28 UTC, alexmurray approved these changes
LGTM!

2023-09-19 11:41 UTC, merged