overlord/devicestate: keep state unlocked when making system runnable
snapcore/snapd pull request #13146
Opened 2023-09-01 12:07 UTC by valentindavid

Making the system runnable will need to seal keys which takes time. So we should not keep the lock.

This fixes `tests/nested/manual/muinstaller-real:encrypted`

2023-09-01 13:11 UTC, valentindavid commented
It have noticed it a bit more complex. I have to refactor the code a bit.

2023-09-05 12:38 UTC, pedronis requested changes
I think we need to be more careful here because afaict there are more paths that potentially go through boot package sealKeyToModeenvUsingFDESetupHook that uses RunFDESetupHook, or use HasFDESetupHook. Sadly I'm not sure we have extensive tests for the fde-setup hook usage

2023-09-05 12:38 UTC, pedronis commented on overlord/devicestate/devicemgr.go
> +	st.Lock()
I'm confused, there's quite a few paths that might end up calling RunFDESetupHook from the boot package as we do boot.RunFDESetupHook = m.runFDESetupHook, maybe we don't have good tests for them but I think more places need to release the lock for this to work but then we hit the issue I mentioned that code in boot is not reentrant/atomic so we need to add some locking there

2023-09-05 12:39 UTC, pedronis commented on overlord/devicestate/devicemgr.go
> +	st.Lock()
Related to this, one test strategy that might help is when mocking in tests a function that depends directly or indirectly on the lock state is to poke the lock from the mocking impl to check the lock is in the right state

2023-10-03 13:46 UTC, closed without merging