boot: lock the modeenv while reading revisions
snapcore/snapd pull request #13332
Opened 2023-10-25 14:30 UTC by valentindavid

`ubuntu-core-20-64:tests/core/system-snap-refresh` fails because of this.

2023-10-25 14:41 UTC, pedronis requested changes

2023-10-25 14:41 UTC, pedronis commented on boot/bootstate20.go
> +
we can't fix it this way,  as other places call this with the lock taken afaik. As I said I think the issue is boot.InUse, but we need to add a unit test using that with a core20 setup

2023-10-25 15:22 UTC, pedronis commented
A possible unit test that fails without the fix:

```
func (s *bootenv20Suite) TestInUse(c *C) {
	coreDev := boottest.MockUC20Device("", nil)
	c.Assert(coreDev.HasModeenv(), Equals, true)
	c.Assert(coreDev.IsCoreBoot(), Equals, true)

	r := setupUC20Bootenv(
		c,
		s.bootloader,
		&bootenv20Setup{
			modeenv: &boot.Modeenv{
				// gadget is gadget1
				Gadget: s.gadget1.Filename(),
				// current kernels is just kern1
				CurrentKernels: []string{s.kern1.Filename()},
				// operating mode is run
				Mode: "run",
				// RecoverySystem is unset, as it should be during run mode
				RecoverySystem: "",
			},
			// enabled kernel is kern1
			kern: s.kern1,
			// no try kernel enabled
			tryKern: nil,
			// kernel status is default
			kernStatus: boot.DefaultStatus,
		})
	defer r()

	inUse, err := boot.InUse(snap.TypeKernel, coreDev)
	c.Check(err, IsNil)
	c.Check(inUse(s.kern1.SnapName(), s.kern1.SnapRevision()), Equals, true)
	c.Check(inUse(s.kern2.SnapName(), s.kern2.SnapRevision()), Equals, false)

	_, err = boot.InUse(snap.TypeBase, coreDev)
	c.Check(err, IsNil)
}
```

2023-10-25 17:45 UTC, Meulengracht approved these changes
Super nice! Thanks to you both @valentindavid and @pedronis - and definitely add in the unit test.

2023-10-26 07:16 UTC, alfonsosanchezbeato approved these changes
LGTM, thanks!

2023-10-26 08:53 UTC, valentindavid commented
Thanks @pedronis, I have added your test, and added the missing Base in the modeenv.

2023-10-26 09:55 UTC, pedronis approved these changes
thx

2023-10-26 15:20 UTC, merged