interfaces/media-control: also allow 'k' (lock)
snapcore/snapd pull request #13355
Opened 2023-11-06 19:21 UTC by dehghanramin

libcamera requires file locking on `/dev/media[0-9]*`. AppArmor denies locking currently, resulting in a _"Pipeline handler in use"_ error. Adding a `k` permission will solve this issue for AppArmor.

2023-11-07 04:23 UTC, alexmurray approved these changes
LGTM!

2023-11-08 07:09 UTC, Meulengracht approved these changes
Thanks, lgtm

2023-11-08 07:30 UTC, olivercalder requested changes
Looks like the unit test needs to be updated as well to expect `rwk` instead of `rw`:

```
FAIL: media_control_test.go:79: MediacontrolInterfaceSuite.TestAppArmorSpec

media_control_test.go:83:
    c.Assert(spec.SnippetForTag("snap.consumer.app"), testutil.Contains, `/dev/media[0-9]* rw,`)
... container string = "" +
...     "\n" +
...     "# Control of media devices\n" +
...     "/dev/media[0-9]* rwk,\n" +
...     "\n" +
...     "# Access to V4L subnodes configuration\n" +
...     "# See [https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/dev-subdev.html\n](https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/dev-subdev.html/n)" +
...     "/dev/v4l-subdev[0-9]* rw,\n"
... elem string = "/dev/media[0-9]* rw,"
```

2023-11-09 07:32 UTC, olivercalder approved these changes
Looks great now, thanks! Once tests pass should be good to go.

2023-11-09 08:31 UTC, dehghanramin commented
> Looks great now, thanks! Once tests pass should be good to go.

Seems like the spread tests are holding it back. Why do they fail so much?

2023-11-09 09:17 UTC, olivercalder commented
Doesn't look like there are any failures on this run (at time of writing), just 4 tests which have yet to complete. We've recently caught some bugs that were causing test failures on Fedora and a few others, and tests should be more consistent now. As these systems and the snapd codebase change, tests have to be updated to adapt, as the way these systems integrate evolves.

2023-11-09 13:33 UTC, merged