many: generalize wording of NFS workaround
snapcore/snapd pull request #13758
Opened 2024-03-27 10:37 UTC by zyga

Ahead of introduction of CIFS workaround, generalize the names so that we use more general language rather instead of focusing on NFS.

As a special exception the externally visible wording related to NFS is kept intact in two places:
 - The apparmor "nfs-support" file name
 - The system key "nfs-home" key.

From points of view this is all an elaborate internal rename that should nto be
observable outside of snapd, apart from log messages that may no longer speak of
NFS but of remote file systems.

2024-03-27 10:40 UTC, zyga commented on osutil/nfs_linux_test.go
> +		comment := Commentf("mountinfo %#v", tc.mountinfo)
This is unrelated, I will remove it.

2024-03-27 12:19 UTC, bboozzoo approved these changes
LGTM

2024-03-27 12:25 UTC, zyga commented on interfaces/system_key.go
> +	// As an exception, the NFSHome is not renamed to RemoteFSHome
heh, yes NFS was the right name all along :)

2024-04-02 08:47 UTC, zyga commented
I've rebased this branch, hoping to get tests more green.

2024-04-02 21:55 UTC, ernestl approved these changes
Looks good, one comment

2024-04-02 21:55 UTC, ernestl commented on osutil/nfs_linux.go
> +// isHomeUsingRemoteFS returns true if NFS mounts are defined or mounted under /home.
"if NFS mounts" in description should probably change?

2024-04-03 08:25 UTC, Meulengracht requested changes
I mean the changes are fine, but what is the point of this? What kinds of remote FSs are relevant of which are not network mounted?

2024-04-03 08:54 UTC, zyga commented
@Meulengracht it's so that we don't only talk about "NFS" the file system, not the concept. The follow-up extends this to support CIFS without saying now it's NFS or CIFS everywhere.

2024-04-03 17:55 UTC, Meulengracht approved these changes
Thanks, i'll +1 this, but I still think `NetworkFS/NFS` is better conceptually as a naming, even with the conflict of NFS the file system. I see very few direct mentions that would specifically refer to the NFS file-system, of which could have been reworded.

2024-04-04 05:41 UTC, bboozzoo commented
needs a rebase

2024-04-04 17:22 UTC, merged