s/cgroup, systemd: escape systemd unit names in CreateTransientScopeForTracking
snapcore/snapd pull request #13763
Opened 2024-03-27 19:16 UTC by andrewphelpsj

With the addition of component hooks, we'll have unit names that include a `+`, like `snap.snapname+comp.hook.install`. This causes systemd to complain that the unit isn't properly escaped. On the command line, systemd-run will properly escape this for you (with a warning), but the dbus API doesn't do that.

2024-03-29 11:24 UTC, bboozzoo submitted a review, later dismissed
LGTM

2024-03-29 11:24 UTC, bboozzoo commented on systemd/escape.go
> +// from it. But that's not in the archive and it won't work with go1.3
hm maybe we should just switch to using go-systemd? It's already an indirect dependency of ours. From the looks of it debian has v22 https://packages.debian.org/search?suite=all&searchon=names&keywords=go-systemd and so does Fedora https://koji.fedoraproject.org/koji/packageinfo?packageID=29480 and there's probably other places we could use it too

2024-04-03 19:27 UTC, pedronis requested changes
I think securityTagFromCgroupPath in scanning.go needs changes to, as it goes back from the cgroup to a tag? do we need unescape support for that?

2024-04-03 20:05 UTC, andrewphelpsj commented
@pedronis what do you think about swapping to using the escape/unescape functions from go-systemd, and getting rid of ours? That'd allow me to use the unescape implementation from there too.

I'm only hesitant because all of our tests don't pass when using that implementation:
```
phelps@ubuntu ~/s/e/systemd> go test

----------------------------------------------------------------------
FAIL: escape_test.go:28: SystemdTestSuite.TestEscapePath

escape_test.go:152:
    c.Check(unit.UnitNamePathEscape(t.in), Equals, t.out, Commentf(t.comment+" (with input %q)", t.in))
... obtained string = "top_level_1-..-top_level_2"
... expected string = "top_level_2"
... invalid path (with input "/top_level_1/../top_level_2/")

escape_test.go:152:
    c.Check(unit.UnitNamePathEscape(t.in), Equals, t.out, Commentf(t.comment+" (with input %q)", t.in))
... obtained string = "\\x9"
... expected string = "\\x09"
... tab character (with input "\t")

OOPS: 117 passed, 1 FAILED
--- FAIL: Test (0.56s)
FAIL
exit status 1
FAIL    github.com/snapcore/snapd/systemd       0.562s
```
I have no clue if these cases are relevant to our use case though. Especially that first case, which has some details in a comment here:
```
// TODO: this case shouldn't work it should cause an error to be
// fully compatible with systemd-escape(1), but it's not documented
// how or why systemd-escape considers this kind of path to be
// invalid, so for now we just process it in an expected and
// deterministic way
```

2024-04-04 13:09 UTC, bboozzoo commented
```
escape_test.go:152:
    c.Check(unit.UnitNamePathEscape(t.in), Equals, t.out, Commentf(t.comment+" (with input %q)", t.in))
... obtained string = "top_level_1-..-top_level_2"
... expected string = "top_level_2"
... invalid path (with input "/top_level_1/../top_level_2/")
```

both implementations seem to be wrong:
```sh
$ systemd-escape -p top_level_1-..-top_level_2
Input 'top_level_1-..-top_level_2' is not an absolute file system path, escaping is likely not going to be reversible.
top_level_1\x2d..\x2dtop_level_2
```

escape_test.go:152:
    c.Check(unit.UnitNamePathEscape(t.in), Equals, t.out, Commentf(t.comment+" (with input %q)", t.in))
... obtained string = "\\x9"
... expected string = "\\x09"
... tab character (with input "\t")
```

yeah, this appears to be wrong, this is what I get:

```sh
$ systemd-escape -p "$(printf '\t')"
Input ' ' is not an absolute file system path, escaping is likely not going to be reversible.
\x09
```

systemd 255

I'd extend some test cases to cover valid snap mount paths and we should be good. We are already quite conservative with what is allowed in the snap/app names, this should be covered.

2024-04-04 16:40 UTC, andrewphelpsj commented
@pedronis after some more reading and some talks with @bboozzoo, it looks like we can't quite use the unescape functions from go-systemd. The reason is that we use the `-` character in the unit names we create right now, which technically should be escaped if we intend it to be a `-`. `systemd-escape --unescape` (and the go-systemd implementation) interprets the `-` as an escaped `/`, we can't use that if we keep using `-` characters in the unit names.

To address this, I introduced two functions for converting between a security tag and a unit name. These functions only really deal with `+`, since we need to maintain the `-` characters, and all of the other characters that might appear in a security tag are already valid unit name characters.

2024-04-05 11:11 UTC, bboozzoo commented on systemd/escape.go
> +//   - "snap.name+comp.hook.install" -> "snap.name\x2bcomp.hook.install"
```suggestion
//   - "snap.name.app" -> "snap.name.app"
//   - "snap.some-name.some-app" -> "snap.some-name.some-app"
//   - "snap.name+comp.hook.install" -> "snap.name\x2bcomp.hook.install"
```

2024-04-05 11:11 UTC, bboozzoo commented on systemd/escape_test.go
> +			tag := systemd.SecurityTagFromUnitName(unit)
Even though it'd be very simple right now a separate unit test for `SecurityTagFromUnitName` would be useful for future refactors.

2024-04-05 17:10 UTC, pedronis approved these changes
thank you, couple small comments

2024-04-05 17:47 UTC, andrewphelpsj commented on snap/naming/tag.go
> +		}
Good call, thank you.

2024-04-11 12:45 UTC, andrewphelpsj commented
blocked until 2.63 is cut

2024-04-17 13:50 UTC, merged