o/ifacestate: properly undo setup-profiles on component installation
snapcore/snapd pull request #13977
Opened 2024-05-17 09:06 UTC by andrewphelpsj

This corrects and tests the behavior of undoing a `setup-profiles` task that contains components. We check if the task is not being done, and in that case we do not consider components that are attached to the task as being set up.

2024-05-23 15:12 UTC, pedronis requested changes
this seems a strange approach unlike any other undo logic

2024-05-23 15:12 UTC, pedronis commented on overlord/snapstate/snapmgr.go
> +		if t.Status() != state.DoingStatus {
it's a bit strange to put the logic here, we do not do this way for any other undo as far as I know

2024-05-23 16:44 UTC, pedronis approved these changes
thanks, small comment

2024-05-23 16:44 UTC, pedronis commented on overlord/ifacestate/handlers.go
> +	appSet, err := appSetForTask(task, snapInfo)
maybe worth adding a comment here, about what is included in the appset

2024-05-23 16:44 UTC, pedronis commented on overlord/ifacestate/handlers.go
> +		appSet, err := appSetForSnapRevision(st, snapInfo)
same here

2024-05-29 15:00 UTC, alfonsosanchezbeato approved these changes
LGTM, thanks

2024-06-03 15:27 UTC, merged