tests: increase `kill-timeout` for auto-refresh-pre-download
snapcore/snapd pull request #14025
Opened 2024-05-30 12:36 UTC by ZeyadYasser

Timeout was noticed to [happen occasionally](https://github.com/snapcore/snapd/actions/runs/9300283020/job/25596467751?pr=13953#step:8:4102), increasing the `kill-timeout` should decrease the likelihood of failing.

2024-05-30 12:57 UTC, sergiocazzolato approved these changes
thanks

2024-05-30 13:03 UTC, MiguelPires requested changes
I don't think the timeout is the problem. I had a look at the logs and we wait quite a bit for an auto-refresh after running `force-autorefresh`. I'm not sure why it never gets triggered, I need to reproduce this and look into the state or add some logging. The kill-timeout is a different issue and is an actual bug how the test handles errors. I'll open a PR to fix that and try to reproduce this. Thanks for bringing this up

2024-05-30 13:51 UTC, MiguelPires commented
I opened https://github.com/snapcore/snapd/pull/14026 to deal with the error handling bug. I'm currently running the test to see if I can reproduce the auto-refresh not triggering. Thanks again!

2024-05-31 05:50 UTC, ZeyadYasser commented
> I opened #14026 to deal with the error handling bug. I'm currently running the test to see if I can reproduce the auto-refresh not triggering. Thanks again!

Thanks! Closing in favor of #14026

2024-05-31 05:50 UTC, closed without merging