tests: fix uc24 nested tests part 2
snapcore/snapd pull request #14069
Opened 2024-06-11 18:59 UTC by sergiocazzolato

This change contains:
    . fixes for model
    . use of core24 snaps (jq, rsync and sh)
    . test fixes
    . using legacy scp in snapd-testing-tools remote-pull (to avoid errors)

2024-06-11 20:41 UTC, alfonsosanchezbeato reviewed
Thanks for this! Some questions below

2024-06-11 20:41 UTC, alfonsosanchezbeato commented on tests/lib/assertions/developer1-24-auto-import.model
Why has this changed? Content of the assertion is the same.

2024-06-11 20:41 UTC, alfonsosanchezbeato commented on tests/lib/external/snapd-testing-tools/remote/remote.pull
> +    $SSH_PASS scp $SSH_CERT -O -P "$TESTS_REMOTE_PORT" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$TESTS_REMOTE_USER"@"$TESTS_REMOTE_HOST":"$REMOTE_PATH" "$LOCA
I'm curious on why is this is needed now...

2024-06-11 20:41 UTC, alfonsosanchezbeato commented on tests/lib/snaps/test-snapd-remodel-pc-min-size-24/meta/gadget.yaml
I'm not sure if the changes here as needed, the mbr should be ignored when remodelling and same for the other changes. Is the test really failing because of this?

2024-06-11 20:41 UTC, alfonsosanchezbeato commented on tests/nested/manual/hybrid-remodel/task.yaml
I actually would prefer to let it fail and research, otherwise this will fall out of our radar.

2024-06-12 03:31 UTC, sergiocazzolato commented on tests/lib/assertions/developer1-24-auto-import.model
I had to change that because in noble the following command failed
`scp -P8022 user1@localhost:/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c .`

I could check that the test tests/nested/manual/core20-set-efi-boot-vars failed to pull any value from /sys/firmware/efi/efivars/ and the issue is gone when we use -O options. 

Need to check why it happens and if there is another way to fix it

2024-06-12 07:06 UTC, Meulengracht requested changes
It's very hard to judge the impact of this PR as there are to many failures in both nested for 22 and 24.

I feel like I need a description of what the result of this PR is supposed to be.

2024-06-12 15:32 UTC, sergiocazzolato commented
This is the status of the nested tests before this branch
2024-06-12 12:30:44 Successful tasks: 49
2024-06-12 12:30:44 Aborted tasks: 33
2024-06-12 12:30:44 Failed tasks: 27

See details in https://paste.ubuntu.com/p/Rj8nM8WdNg/

2024-06-12 20:12 UTC, sergiocazzolato commented on tests/lib/snaps/test-snapd-remodel-pc-min-size-24/meta/gadget.yaml
@valentindavid suggested that change, not sure which is the best solution

2024-06-12 20:25 UTC, alfonsosanchezbeato commented on tests/lib/assertions/developer1-24-auto-import.model
I think you answered to the wrong comment :slightly_smiling_face:

2024-06-12 20:31 UTC, alfonsosanchezbeato commented on tests/lib/external/snapd-testing-tools/remote/remote.pull
> +    $SSH_PASS scp $SSH_CERT -O -P "$TESTS_REMOTE_PORT" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$TESTS_REMOTE_USER"@"$TESTS_REMOTE_HOST":"$REMOTE_PATH" "$LOCA
I've done some checks and what I see is:
* The error happens only when copying from path `/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c` directly. If that file is locally copied to, say, `$HOME`, scp on it works just fine. scp for other files works as well.
* scp 22.04 client can copy `/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c` from a UC24 image just fine
* Verbose traces do not reveal much:
```
scp: debug1: Fetching /sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c to ./BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c

BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8   0%    0     0.0KB/s   --:-- ETA
scp: debug1: truncating at 0
scp: read remote "/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c" : Failure
```

It is therefore possible that this is a scp client bug in noble. At least there is something in the attributes of the file in sysfs that it does not like, athough it is readble for our user.

2024-06-12 21:29 UTC, alfonsosanchezbeato commented on tests/lib/external/snapd-testing-tools/remote/remote.pull
> +    $SSH_PASS scp $SSH_CERT -O -P "$TESTS_REMOTE_PORT" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$TESTS_REMOTE_USER"@"$TESTS_REMOTE_HOST":"$REMOTE_PATH" "$LOCA
Seems definitely an sftp bug, I saw this when reproducing locally:
`Jun 12 21:18:20 qemuname sftp-server[3006]: error: process_read: seek "/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c": Illegal seek
`

2024-06-13 09:11 UTC, Meulengracht approved these changes
Thank you for the description

2024-06-13 13:37 UTC, alfonsosanchezbeato commented on tests/lib/external/snapd-testing-tools/remote/remote.pull
> +    $SSH_PASS scp $SSH_CERT -O -P "$TESTS_REMOTE_PORT" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$TESTS_REMOTE_USER"@"$TESTS_REMOTE_HOST":"$REMOTE_PATH" "$LOCA
I can reproduce in 24.04, and have reported a bug: https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/2069305

2024-06-14 11:59 UTC, valentindavid approved these changes
Looks good.

2024-06-14 12:29 UTC, merged