tets: filter spread logs to be sent to grafana
snapcore/snapd pull request #14127
Opened 2024-06-25 17:53 UTC by sergiocazzolato

Use log-filter tool to generate a .filtered.log file which is sent to grafana.

Those filtered logs don't include the error and debug output, just the executed tests and the results.

2024-06-25 20:24 UTC, olivercalder approved these changes
Looks good to me, thanks!

2024-06-25 21:06 UTC, olivercalder requested changes
Problem with seeing the `log-filter` script in spread tests.

2024-06-25 21:06 UTC, olivercalder commented on .github/workflows/test.yaml
> +          (set -o pipefail; $SPREAD -no-debug-output -logs .logs $RUN_TESTS | ./utils/log-filter $FILTER_PARAMS | tee spread.log)
Spread tests are failing, seems like maybe this should be:

```suggestion
          (set -o pipefail; $SPREAD -no-debug-output -logs .logs $RUN_TESTS | ./tests/lib/external/snapd-testing-tools/utils/log-filter $FILTER_PARAMS | tee spread.log)
```

2024-06-26 14:35 UTC, olivercalder approved these changes
Thanks!

2024-06-27 17:48 UTC, andrewphelpsj approved these changes
Thanks!

2024-06-27 23:39 UTC, merged