github: update PR template to include a checklist
snapcore/snapd pull request #14676
Opened 2024-10-29 09:12 UTC by bboozzoo

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

2024-10-29 11:47 UTC, degville approved these changes
Thanks for doing this - no problems, but a few suggestions.

2024-10-29 11:47 UTC, degville commented on .github/PULL_REQUEST_TEMPLATE.md
> +note if one of those is not applicable):
```suggestion
Please check the following items and add a comment for any that may not apply.
```

2024-10-29 11:47 UTC, degville commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] there are unit tests covering your change
```suggestion
- [ ] unit tests are included for the proposed change
```

2024-10-29 11:47 UTC, degville commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] snapd snap build works with latest snapcraft (snapcraft --verbose)
```suggestion
- [ ] the latest snapcraft version (snapcraft --verbose) builds the snapd snap
```

2024-10-29 11:47 UTC, degville commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] the change needs an entry in the changelog
```suggestion
- [ ] changelog needs to reference this change
```

2024-10-29 13:37 UTC, sergiocazzolato approved these changes
Thanks

2024-11-07 12:05 UTC, Meulengracht approved these changes

2024-11-19 07:58 UTC, ernestl reviewed
Generally looks good, some considerations relating to:
- building with snapcraft as prerequisite
- keeping NEWS.md up to date

2024-11-19 07:58 UTC, ernestl commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] the change needs an entry in the NEWS.md file
During the last few iterations I concluded this is not useful.

(1) We need 100% certainty that nothing is missed, which means I need do what I do and run script to detect all PR's between previous ad current release branch, minus cherry-picked items. From this, test only development as well as internal changes are removed. Then related items (e.g. interface changes) are grouped. Then PR's related to same topic (e.g. components) are summarised. I think this is not possible to get right with run-time news updates.

(2) In addition, having entries in NEWS.md for upcoming release means merging back from release branch is not super trivial as it is without.

2024-11-19 07:58 UTC, ernestl commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] snapd snap build works with latest snapcraft (snapcraft --verbose)
This is (1) rather time consuming and (2) strictly speaking incomplete as it does not include deb artifices.

There is a balance between  running tests upfront to save time/noise in CI failure VS not duplicating expensive test.

2024-12-03 15:44 UTC, ernestl requested changes

2024-12-03 15:44 UTC, ernestl commented on .github/workflows/test.yaml
> +          if [ "${{ matrix.gochannel }}" != "latest/stable" ]; then
This is since covered [here](https://github.com/canonical/snapd/pull/14752).

2026-05-05 14:11 UTC, bboozzoo commented
spring cleanup

2026-05-05 14:11 UTC, closed without merging