tests: use full path to test-snapd-refresh.version binary
snapcore/snapd pull request #9316
Opened 2020-09-10 14:13 UTC by sergiocazzolato

Add full path to the test-snapd-refresh.version binary

This is the error running with external backend:

tests.session -u test exec test-snapd-refresh.version
/tmp/tests.session-4f317b13-6145-488d-9d94-b962b8dc6017/exec: 2: exec:
test-snapd-refresh.version: not found
grep error: pattern not found, got:

2020-09-10 14:17 UTC, zyga requested changes

2020-09-10 14:18 UTC, zyga commented
I think this shows another problem though: we lack the right path entry somehow. CC @bboozzoo for ideas.

2020-09-11 13:51 UTC, sergiocazzolato commented on tests/main/refresh-app-awareness/task.yaml
> +    tests.session -u test exec /snap/bin/test-snapd-refresh.version | MATCH v1
@zyga you mean to do:
su -c 'snap run test-snapd-refresh.version' test | MATCH v1 ?

2020-09-11 14:38 UTC, zyga commented on tests/main/refresh-app-awareness/task.yaml
> +    tests.session -u test exec /snap/bin/test-snapd-refresh.version | MATCH v1
No, I mean `tests.session` that uses `snap run test-snapd-refresh.version`

2020-09-11 16:36 UTC, sergiocazzolato commented on tests/main/refresh-app-awareness/task.yaml
> +    tests.session -u test exec /snap/bin/test-snapd-refresh.version | MATCH v1
@zyga, updated, thanks for the review

2020-09-11 16:58 UTC, anonymouse64 approved these changes
LGTM, with the caveat that we add a TODO to investigate why this is necessary somewhere in tests.session

2020-09-11 18:46 UTC, zyga approved these changes
LGTM, I'll investigate the PATH issue tomorrow.

2020-09-11 18:49 UTC, merged