[RFC] snap-bootstrap: be more robust for recover mode, ignore some errors
snapcore/snapd pull request #9576
Opened 2020-10-30 02:12 UTC by anonymouse64

This is the first take at making recover mode more robust against errors, and
trying to do things anyways even if some things fail on us. This will be
important for robust devices that are still able to get to a recover mode when
things go very very wrong in run mode, and gives snaps that are meant to rescue
the device from recover mode a chance to run and do something about fixing the
device.

This needs tests and obviously needs discussion, but I thought it to be useful to open
before our meeting for folks to take a look at.

2020-10-30 13:09 UTC, pedronis reviewed
I'm slightly confused by some things here. I'm also worried about how the pile of ifs will make tests painful

2020-10-30 13:09 UTC, pedronis commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +	haveHost := true
what does host mean here?

2020-10-30 13:09 UTC, pedronis commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +		// (if it exists) somewhere else
I don't understand this comment,  we mount save to run, no, here?

2020-10-30 13:13 UTC, pedronis commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +		// (if it exists) somewhere else
mmh, I don't think we need this at all. But we need different logic to open save though

2020-10-30 13:15 UTC, pedronis requested changes
some things about save are fairly off here

2020-10-30 13:15 UTC, pedronis commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +		haveSave, err = maybeMountSave(disk, saveDir, isDecryptDev, nil)
this looks wrong, the 2nd argument to maybeMountSave is the place to find it's key, it's not where we mount save

2020-10-30 13:52 UTC, bboozzoo commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +		if isDecryptDev {
Could we use some specific error values instead?

2020-10-30 13:52 UTC, bboozzoo commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +			// to be exposed to userspace
```suggestion
			// userspace to be exposed to
```

2020-10-30 13:52 UTC, bboozzoo commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +	haveHost := true
maybe it should be named haveHostData or haveData and then the other `haveHostSave`?

2020-10-30 13:52 UTC, bboozzoo commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +	// now mount the host partition (if we have it)
.. host ubuntu-data ..

2020-10-30 13:52 UTC, bboozzoo commented on cmd/snap-bootstrap/cmd_initramfs_mounts.go
> +	saveDir := boot.InitramfsHostWritableDir
Shouldn't we always try to mount under /run/mnt/ubuntu-save and let the actual snapd to figure out where to mount save?

2020-11-04 05:03 UTC, anonymouse64 commented
Some of these things are still useful, but in the interest of keeping open PR's low, I will close this and perhaps re-open it later, or otherwise split the useful bits out into different PR's

2020-11-04 05:03 UTC, closed without merging

2020-11-04 05:04 UTC, anonymouse64 commented
also this largely has been superceded by https://github.com/snapcore/snapd/pull/9592