o/devicestate,daemon: fix reboot system action to not require a system label
snapcore/snapd pull request #9694
Opened 2020-11-24 17:35 UTC by anonymouse64

We should be able to trigger a reboot without specifying the system label, since
we can detect the current system label and use that for the specified mode.

This was not caught before because of how we test daemon command endpoints and
the fact that the router we use operates weirdly for paths like /v2/systems,
where we have separate commands for the version without any sub-path and the
version with a sub-path.

2020-11-25 10:02 UTC, pedronis requested changes
I'm not sure I understand the need/reason for the change in devicemanager, if it's really needed to make the spread test pass then we have another bug either in client or daemon

2020-11-25 17:04 UTC, anonymouse64 commented on overlord/devicestate/devicemgr.go
> +		systemMode := m.SystemMode()
yes I was confused we didn't need this, we just needed the daemon routing bits

2020-11-25 17:04 UTC, anonymouse64 commented on daemon/api_systems.go
> +	// XXX: this is awkward, we want the postSystemsAction function to be used
removed

2020-11-25 17:10 UTC, pedronis approved these changes
thanks

2020-11-26 13:51 UTC, mvo5 approved these changes

2020-11-30 08:07 UTC, merged

2020-12-10 20:35 UTC, anonymouse64 commented
note to myself, this will be in 2.48.2, not 2.48 or 2.48.1