interfaces/builtin: Allow DBus property access on org.freedesktop.Notifications
snapcore/snapd pull request #9840
Opened 2021-01-14 12:45 UTC by kbroulik

This allows access to e.g. the "Inhibited" property in KDE Plasma 5.16+ that indicates
whether "Do not disturb" mode is enabled.

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

---
This is for example used by Telegram to turn off own notification popups and sounds when notifications are inhibited.

2021-01-14 12:59 UTC, bboozzoo approved these changes
LGTM. Thank you!

2021-01-14 15:09 UTC, mvo5 approved these changes
Looks good to me as well

2021-01-15 04:43 UTC, alexmurray commented
LGTM too from a security point-of-view - note this property does not appear to be supported by gnome-shell currently so on a GNOME desktop you will see an error when trying to access it:
```
Error org.freedesktop.DBus.Error.InvalidArgs: No such property “Inhibited”
```

It is also not part of the official freedesktop notification spec either from what I can see in https://gitlab.freedesktop.org/xdg/xdg-specs/-/blob/master/notification/notification-spec.xml

2021-01-15 04:44 UTC, alexmurray commented on interfaces/builtin/desktop.go
> +dbus (send)
Can you please add a comment here about why this is required (ie for the Inhibited property) and then also a link to some upstream KDE documentation which documents this property?

2021-01-15 04:45 UTC, alexmurray requested changes
Can this please include a link to some upstream KDE documentation that mentions this new Inhibited property?

2021-01-15 13:22 UTC, kbroulik commented
Yeah, it's proprietary to Plasma. I've tried to augment the notification spec for a year but gave up at this point. [1]

[1] https://invent.kde.org/plasma/plasma-workspace/-/blob/master/libnotificationmanager/dbus/org.freedesktop.Notifications.xml#L42

2021-01-19 09:07 UTC, pedronis commented
marking blocked until the comment is added in the code itself

2021-01-19 11:28 UTC, bboozzoo commented
I see that the comment was added but without URL. When it's green we should probably land it and I can push the URL in a followup commit if that's ok.

2021-01-19 20:24 UTC, kbroulik commented
Given CI keeps randomly failing, so this couldn't be merged, I've now added the URL, too.

2021-01-19 21:20 UTC, anonymouse64 approved these changes

2021-01-20 08:06 UTC, merged